config/routes.rb
SiteTools::Application.routes.draw do

  mount SecureResqueServer.new, :at => '/resque'

  resources :sites do
    resources :broken_links
  end
  resources :spelling_errors
  match 'signin' => 'users#signin', :as => 'signin'
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  match 'dashboard' => 'users#dashboard', :as => :dashboard

  root :to => 'users#dashboard'
  
  

end

app/models/broken_link.rb
class BrokenLink
  include Mongoid::Document
  field :url, type: String
  field :dom_elem, type: String # <a href='http://domain.com'>text</a>
  field :link_type, type: Integer # 1=>internal, 0=>external
  field :recommendation, type: String
  field :details, type: String
  field :status_code, type: Integer # 200, 404 or 500

  belongs_to :site
end

app/controllers/broken_links_controller.rb
class BrokenLinksController < ApplicationController
  before_filter :check_site

  # GET /broken_links/1
  # GET /broken_links/1.json
  def show
    @broken_link = @site.broken_links.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @broken_link }
    end
  end

  # GET /broken_links/1/edit
  def edit
    @broken_link = @site.broken_links.find(params[:id])
  end

  # PUT /broken_links/1
  # PUT /broken_links/1.json
  def update
    
  end

  # DELETE /broken_links/1
  # DELETE /broken_links/1.json
  def destroy
    @broken_link = @site.broken_links.find(params[:id])
    @broken_link.destroy

    respond_to do |format|
    format.html { redirect_to @site }
      format.json { head :no_content }
    end
  end

  def check_site
    @site = current_user.sites.find(params[:site_id])
  end
end

app/helpers/broken_links_helper.rb
module BrokenLinksHelper
end

app/views/broken_links/_broken_links.haml
%table.table.table-striped.broken_links_tab
  %tr
    %th URL
    %th dom_elem
    %th Link type
    %th Recommendation
    %th Details
    %th.actions= t("shared.action")
  - @broken_links.each do |broken_link|
    %tr
      %td= broken_link.url
      %td= broken_link.dom_elem
      %td= broken_link.link_type
      %td= broken_link.recommendation
      %td= broken_link.details
      %td.actions
        = link_to '', site_broken_link_path(@site, broken_link), class: "icon-check"
        = link_to '', edit_site_broken_link_path(@site, broken_link), class: "icon-edit"
        = link_to '', site_broken_link_path(@site, broken_link), method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-trash"
= will_paginate @broken_links, renderer: BootstrapPagination::Rails, previous_label: t("links.pre_page"), next_label: t("links.next_page")

app/views/broken_links/_form.html.haml
= form_for [@site, @broken_link] do |f|
  - if @broken_link.errors.any?
    #error_explanation
      %h2= "#{pluralize(@broken_link.errors.count, "error")} prohibited this broken_link from being saved:"
      %ul
        - @broken_link.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :url
    = f.text_area :url
  .field
    = f.label :dom_elem
    = f.text_area :dom_elem
  .field
    = f.label :link_type
    = f.number_field :link_type
  .field
    = f.label :recommendation
    = f.text_area :recommendation
  .field
    = f.label :details
    = f.text_area :details
  .actions
    = f.submit 'Save'

app/views/broken_links/edit.html.haml
%h1 Editing broken_link

= render 'form'

= link_to 'Show', site_broken_link_path(@broken_link)
\|
= link_to 'Back', site_broken_link_path(@broken_link)

app/views/broken_links/new.html.haml
%h1 New broken_link

= render 'form'

= link_to 'Back', broken_links_path

app/views/broken_links/show.html.haml
%p#notice= notice

%p
  %b Url:
  = @broken_link.url
%p
  %b Dom elem:
  = @broken_link.dom_elem
%p
  %b Link type:
  = @broken_link.link_type
%p
  %b Recommendation:
  = @broken_link.recommendation
%p
  %b Details:
  = @broken_link.details

= link_to 'Edit', edit_site_broken_link_path(@broken_link)
\|
= link_to 'Back', edit_site_broken_link_path(@broken_link)