config/routes.rb
SiteTools::Application.routes.draw do

  mount SecureResqueServer.new, :at => '/resque'

  resources :sites do
    resources :broken_links
  end
  resources :spelling_errors
  match 'signin' => 'users#signin', :as => 'signin'
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  match 'dashboard' => 'users#dashboard', :as => :dashboard

  root :to => 'users#dashboard'
  
  

end

app/models/site.rb
class Site
  require 'nokogiri'
  require 'open-uri'

  include Mongoid::Document
  field :url, type: String
  field :name, type: String

  belongs_to :user
  has_many :broken_links, dependent: :delete
  has_many :spelling_errors, dependent: :delete
  
  cattr_accessor :current_user

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  # GET /sites.json
  def index
    @sites = current_user.sites.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = current_user.sites.find(params[:id])
    @external_broken_links = @site.broken_links.where(:link_type => 0).paginate(page: params[:page])
    @internal_broken_links = @site.broken_links.where(:link_type => 1).paginate(page: params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = current_user.sites.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = current_user.sites.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = current_user.sites.build(params[:site])

    respond_to do |format|
      if @site.save
        Resque.enqueue(CheckLinksJob, @site.id)
        format.html { redirect_to sites_path, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = current_user.sites.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = current_user.sites.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end
end

app/views/sites/_form.html.haml
= form_for @site do |f|
  - if @site.errors.any?
    #error_explanation
      %h2= "#{pluralize(@site.errors.count, "error")} prohibited this site from being saved:"
      %ul
        - @site.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/sites/index.html.haml
%h1 Listing Sites

%table.table.table-striped.site_list
  %tr
    %th Site Name
    %th Base URL
    %th= t("shared.action")

  - @sites.each do |site|
    %tr
      %td= site.name
      %td= site.url
      %td
        = link_to '', site, class: "icon-check"
        = link_to '', edit_site_path(site), class: "icon-edit"
        = link_to '', site, method: :delete, data: { confirm: 'Are you sure?' }, class: "icon-trash"
= link_to 'New Site', new_site_path, class: "btn"
:javascript
  $(document).ready(function(){
    $(".navbar-inner li").removeClass("active");
    $(".navbar-inner").find(".sites").addClass("active");
  })

app/views/sites/new.html.haml
%h1 New Site

= render 'form'

= link_to t('shared.back'), sites_path, class: "btn"

app/views/sites/show.html.haml
%p#notice= notice
-#= render 'layouts/site_summary'
.tabbable
  %ul.nav.nav-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#internal_links"}= t("links.internal_links")
    %li
      %a{"data-toggle" => "tab", href: "#external_links"}= t("links.external_links")
  .tab-content
    #internal_links.tab-pane.active
      = render partial: "broken_links/broken_links", :locals => { :@broken_links => @external_broken_links }
    #external_links.tab-pane
      = render partial: "broken_links/broken_links", :locals => { :@broken_links => @internal_broken_links }

:javascript
  $(document).ready(function(){
    $('.sites .btn').html('#{@site.name}');
    $('.sites .btn').append('<span class="caret"></span>');

    $(".navbar-inner li").removeClass("active");
    $(".navbar-inner").find(".sites").addClass("active");
  });