config/routes.rb
SiteTools::Application.routes.draw do

  mount SecureResqueServer.new, :at => '/resque'

  resources :sites do
    resources :broken_links
  end
  resources :spelling_errors
  match 'signin' => 'users#signin', :as => 'signin'
  match 'logout' => 'users#logout', :as => :logout
  match 'signup' => 'users#signup', :as => :signup
  match 'dashboard' => 'users#dashboard', :as => :dashboard

  root :to => 'users#dashboard'
  
  

end

app/views/layouts/_header.html.haml
.navbar
  .navbar-inner
    %a.brand{:href => "/dashboard"} DashBoard
    %ul.nav.top_left_nav
      %li.home.active
        %a{:href => "/"} Home
      - if current_user.nil?  
        %li.signin
          %a{:href => "/signin"} Sign In
        %li.signup
          %a{:href => "/signup"} Sign Up
      - else
        %li.sites.dropdown
          %a{"href" => "#", "data-toggle" => "dropdown"}
            Sites
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to t("sites.all"), sites_path
        %li.site_summary
          %a{ :href => '#' }Site Summary
        %li.setting.dropdown
          %a{"href" => "#", "data-toggle" => "dropdown"}
            Setting
            %b.caret
          %ul.dropdown-menu
            %li
              %a{ :href => '#' } My Account
            %li
              %a{ :href => '#' } Add Account
        %li.help.dropdown
          %a{"href" => "#", "data-toggle" => "dropdown"}
            Help
            %span.caret
          %ul.dropdown-menu
            %li
              %a{ :href => '#' } Tips
            %li
              %a{ :href => '#' } Surport
        %li.logout
          %a{:href => "/logout"} Log Out

app/views/layouts/_site_summary.haml
.container-fluid
  .rows
    .left_content.span2.bs-docs-sidebar
      .broken_links
        %span BROKEN LINKS
        %span.unfold_sub_menu.icon-minus
        %ul.nav.nav-pills.nav-stacked.left_nav
          %li.active
            %a.broken_external_link{:href=>'#'} Broken external link
          %li
            %a.broken_internal_link{:href=>'#'} Broken internal link
      .spelling_error
        %span SPELLING
        %span.unfold_sub_menu.icon-plus
        %ul.nav.nav-pills.nav-stacked.left_nav.hide
          %li
            %a.spelling_error{ :href=>'#' } Likely spelling errors
      .Accessibility
        %span ACCESSIBILITY
        %span.unfold_sub_menu.icon-plus
        %ul.nav.nav-pills.nav-stacked.left_nav.hide
          %li
            %a{ :href=>'#' } Character set
          %li
            %a{ :href=>'#' } Embed tags
          %li
            %a{ :href=>'#' } Form labels
          %li
            %a{ :href=>'#' } Formatting tags
          %li
            %a{ :href=>'#' } Headers
          %li
            %a{ :href=>'#' } Image alt or title attribute 
          %li
            %a{ :href=>'#' } Inconsistent link text
          %li
            %a{ :href=>'#' } Inline styles
          %li
            %a{ :href=>'#' } Input names
          %li
            %a{ :href=>'#' } Language code
          %li
            %a{ :href=>'#' } Legend text
          %li
            %a{ :href=>'#' } Nested tables
          %li
            %a{ :href=>'#' } Poor link text
          %li
            %a{ :href=>'#' } Refresh meta element
          %li
            %a{ :href=>'#' } Table summaries
          %li
            %a{ :href=>'#' } Tables for layout
          %li
            %a{ :href=>'#' } Tables headings
          %li
            %a{ :href=>'#' } Title attribute
          %li
            %a{ :href=>'#' } Title exist
      .seo
        %span SEO
        %span.unfold_sub_menu.icon-plus 
        %ul.nav.nav-pills.nav-stacked.left_nav.hide
          %li
            %a{ :href=>'#' } Description too long
          %li
            %a{ :href=>'#' } Document title length
          %li
            %a{ :href=>'#' } Meta description exists
          %li
            %a{ :href=>'#' } SEO Image description
          %li
            %a{ :href=>'#' } SEO Page refresh
          %li
            %a{ :href=>'#' } SEO Titles exist
          %li
            %a{ :href=>'#' } SEO headings
          %li
            %a{ :href=>'#' } SEO title attribute 
          %li
            %a{ :href=>'#' } Single h1 in document
          %li
            %a{ :href=>'#' } Spaces in url
    .right_content.span10  WELCOME
:javascript
  $(document).ready(function(){
    var top_lis = $('.navbar-inner ul.nav li');
    top_lis.removeClass('active');
    top_lis.filter('.home').addClass('active');

    var left_nav_lis = $('.left_nav li');
    left_nav_lis.bind('click', function(){
      left_nav_lis.removeClass('active');
      $(this).addClass('active');
    })

    var links = $('.left_nav a');
    links.bind('click', function(){
      var me = $(this),
          _request_url,
          _data = {},
          _callback,
          _beforeSend;
      if(me.hasClass('broken_external_link')){
        _data.link_type = 0;
        _request_url = app_url + '/broken_links';
      }else if(me.hasClass('broken_internal_link')){
        _data.link_type = 1;
        _request_url = app_url + '/broken_links';
      }else if(me.hasClass('spelling_error')){
        _request_url = app_url + '/spelling_errors.json';
      }
      _data.site_id = '#{@site.id}'
      _callback = function(resp_text){
        $('.right_content').html(resp_text);
        $('img.loading_img').remove();
      };
      _beforeSend= function(){
        $('.right_content').html('');
        $('.right_content').append(loading_img);
      };
      sendAjaxRequest(_request_url, _data, 'json', 'get', _beforeSend, _callback);
    })
  });

  $(document).ready(function(){
    $('.unfold_sub_menu').bind('click', function(){
      var me = $(this);
      me.toggleClass('icon-plus icon-minus');
      me.next('ul').toggleClass('hide');
    })
  })

  $(document).ready(function(){
    $('.broken_external_link').trigger('click');
  });

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Site Tools
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render "layouts/header"

    .container
      = yield